<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-NG3RBDE" failures="1" tests="6" name="Runner_files.Signup_negative_scenario_runner" time="56.160" errors="0" timestamp="2021-05-07T12:15:05 IST" skipped="0">
  <testcase classname="Runner_files.Signup_negative_scenario_runner" name="runScenario" time="5.143"/>
  <system-out/>
  <testcase classname="Runner_files.Signup_negative_scenario_runner" name="runScenario" time="4.687"/>
  <system-out/>
  <testcase classname="Runner_files.Signup_negative_scenario_runner" name="runScenario" time="5.176"/>
  <system-out/>
  <testcase classname="Runner_files.Signup_negative_scenario_runner" name="runScenario" time="4.987"/>
  <system-out/>
  <testcase classname="Runner_files.Signup_negative_scenario_runner" name="runScenario" time="19.012"/>
  <system-out/>
  <testcase classname="Runner_files.Signup_negative_scenario_runner" name="runScenario" time="17.155">
    <failure message="expected [Phone no already exists.] but found [Phone number required]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Phone no already exists.] but found [Phone number required]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at Signup_negative_scenario.Signup_negative_scenario.signup_negative_tc_006(Signup_negative_scenario.java:144)
at âœ½.User enters already registered phone number(file:///C:/Users/Admin/Downloads/Regression_test_suite_Android/src/main/java/Signup_negative_scenario/Signup_negative_scenario.feature:25)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Runner_files.Signup_negative_scenario_runner -->
